name: Test RSS generation

on:
   schedule:
     - cron: "0 */2 * * *"

jobs:
  gene-rss:
    runs-on: ubuntu-latest
    name: A job to test RSS generation
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test Rssify
      uses: tabhub/rssify@v2
      with:
        title: okinawatimes
        url: https://www.okinawatimes.co.jp/category/news-original
        item-title-css: a.c-card.c-card--vertical > div > div.c-card__title
        item_description_selector: a.c-card.c-card--vertical > div > div.c-card__title
        item-url-css: a.c-card.c-card--vertical[href]
        item-date-css: a.c-card.c-card--vertical > div > div.c-card__title > div > time
        item-timezone: Japan
